workflows:
  debug-workflow:
    name: Native Android
    max_build_duration: 60
    scripts:
      - |
        # launching android emulator
        emulator -avd emulator > /dev/null 2>&1 &
      - |
        # set up debug keystore
        rm -f ~/.android/debug.keystore
        keytool -genkeypair \
          -alias androiddebugkey \
          -keypass android \
          -keystore ~/.android/debug.keystore \
          -storepass android \
          -dname 'CN=Android Debug,O=Android,C=US' \
          -keyalg 'RSA' \
          -keysize 2048 \
          -validity 10000
      - |
        # build debug apk
        ./gradlew assembleDebug
    artifacts:
      - app/build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - hfararjeh98@gmail.com
